### ISSUE TITLE
广告打的挺响的，一看代码写得真烂

### ISSUE THREAD

**Issue by 474846718** [roncoo/roncoo-pay#43]
这就是国内多名从事互联网金融项目工作的人员的编码水平，我觉得这种代码要是被人说是我写的我都觉得丢脸。

**Comment by the404** [comment]
just a stupid pig

**Comment by piggytrip** [comment]
> 这就是国内多名从事互联网金融项目工作的人员的编码水平，我觉得这种代码要是被人说是我写的我都觉得丢脸。

本来准备用别人的代码的，你这么说，我都不敢用了

**Comment by yy306525121** [comment]
正准备借鉴一下呢,  发现一堆问题

**Comment by 474846718** [comment]
> 
> 
> > 这就是国内多名从事互联网金融项目工作的人员的编码水平，我觉得这种代码要是被人说是我写的我都觉得丢脸。
> 
> 本来准备用别人的代码的，你这么说，我都不敢用了

一堆map传参恶心得一批，一加载到idea就各种警告！代码里一点面向对象的思想都没有！
