### ISSUE TITLE
maven alipay 报错

### ISSUE THREAD

**Issue by okoala** [roncoo/roncoo-pay#6]
![image](https://cloud.githubusercontent.com/assets/2127199/17590006/7036eca6-600a-11e6-9d5f-d8d5c87f84b4.png)

我在maven怎么没有搜到alipay trade sdk 模块

**Comment by leslie52** [comment]
在service工程的lib文件夹下有，加载下就可以了

**Comment by okoala** [comment]
谢谢~搞定
